# Generated by Django 6.0.4 on 2026-05-14 16:22
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('a_app_name', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.TextField(max_length=4, null=True),
        ),
    ]