# Generated by Django 6.0.4 on 2026-05-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_app_name', '0004_author_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publisher',
        ),
    ]
